/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ContentItem = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'contentType' : IDL.Text,
  'file' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
  'language' : IDL.Text,
  'category' : IDL.Text,
  'classLevel' : IDL.Text,
  'governmentApproved' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GroupView = IDL.Record({
  'id' : IDL.Text,
  'members' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const PerformanceData = IDL.Record({
  'topic' : IDL.Text,
  'total' : IDL.Nat,
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'classOrBranch' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'language' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBadge' : IDL.Func([IDL.Text], [], []),
  'addContentItem' : IDL.Func([ContentItem], [], []),
  'addMemberToGroup' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addQuote' : IDL.Func([IDL.Text], [], []),
  'addXP' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGroup' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteContentItem' : IDL.Func([IDL.Text], [], []),
  'getAllContentItems' : IDL.Func([], [IDL.Vec(ContentItem)], ['query']),
  'getAllGroups' : IDL.Func([], [IDL.Vec(GroupView)], ['query']),
  'getAllPerformanceData' : IDL.Func([], [IDL.Vec(PerformanceData)], ['query']),
  'getAllQuotes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getBadges' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContentItem' : IDL.Func([IDL.Text], [IDL.Opt(ContentItem)], ['query']),
  'getContentItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContentItem)],
      ['query'],
    ),
  'getContentItemsByClassLevel' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContentItem)],
      ['query'],
    ),
  'getGroup' : IDL.Func([IDL.Text], [IDL.Opt(GroupView)], ['query']),
  'getPerformanceData' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PerformanceData)],
      ['query'],
    ),
  'getQuizScore' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Nat)], ['query']),
  'getRandomContentItemByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ContentItem)],
      ['query'],
    ),
  'getRandomQuote' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getRecentPerformanceData' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PerformanceData)],
      ['query'],
    ),
  'getStudyPlan' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  'getTopPerformanceData' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PerformanceData)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getXP' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Nat)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePerformanceData' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'saveQuizScore' : IDL.Func([IDL.Nat], [], []),
  'saveStudyPlan' : IDL.Func([IDL.Text], [], []),
  'updateContentItem' : IDL.Func([ContentItem], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ContentItem = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'contentType' : IDL.Text,
    'file' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
    'language' : IDL.Text,
    'category' : IDL.Text,
    'classLevel' : IDL.Text,
    'governmentApproved' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GroupView = IDL.Record({
    'id' : IDL.Text,
    'members' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const PerformanceData = IDL.Record({
    'topic' : IDL.Text,
    'total' : IDL.Nat,
    'score' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'classOrBranch' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'language' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBadge' : IDL.Func([IDL.Text], [], []),
    'addContentItem' : IDL.Func([ContentItem], [], []),
    'addMemberToGroup' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addQuote' : IDL.Func([IDL.Text], [], []),
    'addXP' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGroup' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteContentItem' : IDL.Func([IDL.Text], [], []),
    'getAllContentItems' : IDL.Func([], [IDL.Vec(ContentItem)], ['query']),
    'getAllGroups' : IDL.Func([], [IDL.Vec(GroupView)], ['query']),
    'getAllPerformanceData' : IDL.Func(
        [],
        [IDL.Vec(PerformanceData)],
        ['query'],
      ),
    'getAllQuotes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getBadges' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContentItem' : IDL.Func([IDL.Text], [IDL.Opt(ContentItem)], ['query']),
    'getContentItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContentItem)],
        ['query'],
      ),
    'getContentItemsByClassLevel' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContentItem)],
        ['query'],
      ),
    'getGroup' : IDL.Func([IDL.Text], [IDL.Opt(GroupView)], ['query']),
    'getPerformanceData' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PerformanceData)],
        ['query'],
      ),
    'getQuizScore' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Nat)], ['query']),
    'getRandomContentItemByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ContentItem)],
        ['query'],
      ),
    'getRandomQuote' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getRecentPerformanceData' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PerformanceData)],
        ['query'],
      ),
    'getStudyPlan' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
    'getTopPerformanceData' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PerformanceData)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getXP' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Nat)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePerformanceData' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'saveQuizScore' : IDL.Func([IDL.Nat], [], []),
    'saveStudyPlan' : IDL.Func([IDL.Text], [], []),
    'updateContentItem' : IDL.Func([ContentItem], [], []),
  });
};

export const init = ({ IDL }) => { return []; };