/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContentItem {
  'id' : string,
  'url' : string,
  'title' : string,
  'subject' : string,
  'contentType' : string,
  'file' : [] | [ExternalBlob],
  'description' : string,
  'language' : string,
  'category' : string,
  'classLevel' : string,
  'governmentApproved' : boolean,
}
export type ExternalBlob = Uint8Array;
export interface UserProfile {
  'classOrBranch' : string,
  'name' : string,
  'role' : string,
  'email' : string,
  'language' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContentItem' : ActorMethod<[ContentItem], undefined>,
  'addQuote' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGroup' : ActorMethod<[string, string, string], undefined>,
  'deleteContentItem' : ActorMethod<[string], undefined>,
  'getAllContentItems' : ActorMethod<[], Array<ContentItem>>,
  'getAllQuotes' : ActorMethod<[], Array<string>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContentItem' : ActorMethod<
    [string],
    {
      'url' : string,
      'title' : string,
      'subject' : string,
      'contentType' : string,
      'file' : [] | [ExternalBlob],
      'description' : string,
      'language' : string,
      'category' : string,
      'classLevel' : string,
      'governmentApproved' : boolean,
    }
  >,
  'getContentItemsByCategory' : ActorMethod<[string], Array<ContentItem>>,
  'getContentItemsByClassLevel' : ActorMethod<[string], Array<ContentItem>>,
  'getQuizScore' : ActorMethod<[Principal], [] | [bigint]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveQuizScore' : ActorMethod<[bigint], undefined>,
  'updateContentItem' : ActorMethod<[ContentItem], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];